export * from './http';
export * from './common';
export { RightConsents } from './api';
export * as ConsentsResource from './consents';
export * as KeysResource from './keys';
export * as ModelsResource from './models';
export * as ReceiptsResource from './receipts';
export * as RecordsResource from './records';
export * as StatsResource from './statistics';
export * as SubjectsResource from './subjects';
export * as SystemResource from './system';
export * as TokensResource from './tokens';
export * as UsersResource from './users';
export { DataFormWrapper, ConsentFormWrapper, ConsentCollector } from './forms';
export declare const version = "v1.3.0";
